receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  elasticsearch:
    endpoints: ["http://cashflow-elasticsearch:9200"]
    logs_index: "logs"
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticsearch, logging]
